name: RCB Ticket Monitor

on:
  schedule:
    # Run every 30 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  monitor-tickets:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run ticket monitor script
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        PAGERDUTY_ROUTING_KEY: ${{ secrets.PAGERDUTY_ROUTING_KEY }}
      run: python rcb_ticket_monitor.py